### ISSUE TITLE
Use different text styles

### ISSUE THREAD

**Issue by J-Cake** [SnapperTT/sdl_stb_font#1]
Is there a *way* to ~make~ _text_ **stylised**? :P

I'm just wondering if there is support for such features? Otherwise, really easy to use library. Nice work :+1:

**Comment by SnapperTT** [comment]
Not natively. You'll have to do it manually (load fonts for each style, chunk your string based on styles, process line by line, render the segments in the correct position). You'll also have to come up with a styling format

I just threw together an update that lets you call an overloaded `drawText(x, y, string, xOut, yOut)`. You can also use the existing `renderToTexture` as it provides size output

I am open to the idea -- and also inline colour -- any suggestions as how to incorporate format codes? bbcode could work, as could ANSI escape codes

EDIT: I have an idea. A class could contain an array of string chunks + format types. Think `std::vector<std::tuple<string, formatStyle, r, g, b, a> >`. You could populate this class by using it like a stream - eg:

```
formattedStringObj << regular_text
    << format::bold << bold_text
    << format::regular << no_longer_bold_text
    << format::color(255,0,4,255) << custom_color_text;
```
The library would then automagically do what I suggested at the top of this post. It would up to the user to implement format codes + parsing

**Comment by J-Cake** [comment]
I think the stream idea sounds fantastic, Maybe if it's possible to use numerical identifiers for different styles, that could allow the user to specify the styles with bitwise or like the streaming example you suggested. This would also work with colours.

```
str << "Hello" << format::bold | format::italic << format.colour(255, 125, 125) << "Bold+Italic+Red Text" << format::regular << "Normal"
```
^ I like that a lot.

Otherwise, loading font files containing different styles seems like a good suggestion.

**Comment by SnapperTT** [comment]
Feature has been added

**Comment by J-Cake** [comment]
Dude you're a machine!!! This is awesome!!
