### ISSUE TITLE
Text Measuring is returning incorrect sizes

### ISSUE THREAD

**Issue by J-Cake** [SnapperTT/sdl_stb_font#2]
Hi, sorry for bothering you again, I'd just noticed that I'm getting inaccurate text sizes when using the `getTextSize()` method. In this included screenshot, I'm wanting to place two elements of text next to each other. I do this by setting the `x` coordinate of the second to that of the first, plus the first's width. Unfortunately, this isn't quite working. I've added a method to load a font just before the text is measured to no avail. 
![capture_2020-11-06_23:09:02](https://user-images.githubusercontent.com/29561775/98364757-7a540d00-2085-11eb-8988-e122f69953b0.png)

```cpp
sdl_stb_formatted_text text;
text << "Hello";
    
int w, h;
sdl2::fc.getTextSize(w, h, text);

...

sdl_stb_formatted_text text;
text << "Bye";
    
int w, h;
sdl2::fc.getTextSize(w, h, text);
```

The returned dimensions for each are `w: 32, h: 20` and `w: 24, h: 20` respectively.

**Comment by SnapperTT** [comment]
Does unformatted text (not using the sdl_std_formatted_text class) produce the same error?

**Comment by J-Cake** [comment]
yea, it does

**Comment by SnapperTT** [comment]
The following is working fine for me (copy pasted into the example)

```
	int offset = 0;			
	{
	sdl_stb_formatted_text text;
	text << "Hello";
	int w, h;
	fc.getTextSize(w, h, text);
	std::cout << "Text size: " << w << ", " << h << std::endl;
	
	fc.drawText(0, 200, text);
	offset = w;
	}
	
	{
	sdl_stb_formatted_text text;
	text << "Bye";
	int w, h;
	fc.getTextSize(w, h, text);
	std::cout << "Text size: " << w << ", " << h << std::endl;
	fc.drawText(offset, 200, text);
	}
```
Are you sure you're adding `width + x` and not `height + x`? Can you post your exact math code?

Also you can use the returned value of `int drawText()` to get the end position of a rendered string/formatted text object. I've made an internal change so that `sdl_stb_prerendered_text::draw()` now does the same.

**Comment by J-Cake** [comment]
Okay, so I pasted your example into a sample function and got the same results. To confirm, the code is this:

```cpp
    int offset = 0;			
	{
        sdl_stb_formatted_text text;
        text << "Hello";
        int w, h;
        sdl2::fc.getTextSize(w, h, text);
        std::cout << "Text size: " << w << ", " << h << std::endl;
        
        sdl2::fc.drawText(0, 200, text);
        offset = w;
	}
	
	{
        sdl_stb_formatted_text text;
        text << "Bye";
        int w, h;
        sdl2::fc.getTextSize(w, h, text);
        std::cout << "Text size: " << w << ", " << h << std::endl;
        sdl2::fc.drawText(offset, 200, text);
	}
```
the only difference being formatting

**Comment by SnapperTT** [comment]
Some ideas:
Is the font file the same as the example?
Does changing the face size of the font move around the relative position of Bye to Hello?
Is the return value of `drawText(x,y, text) == x + w`?
Are you using High DPI?

**Comment by J-Cake** [comment]
Okay, so I set up a dummy application where the program works as expected. 

1) yes, the font file is the same
2) no, their positions remain unaffected relative to each other
3) 
```
Text size: 32, 20
32 == 32
Text size: 24, 20
24 == 56
```
4) No, I'm not using HiDPI (I think, I'm not sure. A calculator revealed I have ~150 DPI but I have no idea how that relates to HiDPI settings etc)

**Comment by SnapperTT** [comment]
Your dummy app is WAD, but your actual app is broken?

With `fc.faceSize = 20` I can replicate that "Hello" has a width of 32px and "Bye" has a width of 24px, and that rendering "Bye" at x=32 places it correctly next to "Hello"

**Comment by J-Cake** [comment]
That's annoying because that means the issue is internal to my application and I have to do some extra issue tracking

**Comment by SnapperTT** [comment]
I've replicated your issue by setting the x position of Bye to the height and not width of Hello. Can you 100% confirm for me that this is not what is happening on your end?

![image](https://user-images.githubusercontent.com/4939563/98426135-6ccd7000-20e3-11eb-9931-8cb793e5f268.png)

**Comment by J-Cake** [comment]
Interestingly, I'm noticing an awful similarity between my result and yours. Although I can't find any misreference throughout my code, this seems like a very plausible error

**Comment by J-Cake** [comment]
Status Update: My incompetence has lead to me not being thorough with refactoring - I was indeed using the reversed coordinates in a place where I didn't even think to look.

**Comment by J-Cake** [comment]
I did want to ask however why there is only  `getTextHeight()` and not an equivalent `getTextWidth()`?

**Comment by SnapperTT** [comment]
`getTextHeight` just counts the newlines in the string and returns `nNewLines * rowSize`. Its relatively fast. A `getTextWidth` needs to process each glyph and is therefore slower, and you get the height for essentially free anyway, so internally there's no real difference between that and `getTextSize`. I enforce the use of `getTextSize` to prevent people from calling `getTextWidth` and `getTextHeight` on the same string.

**Comment by J-Cake** [comment]
Ah yes, that makes sense. Thanks for helping me out
